### ISSUE TITLE
verifyProof error on nested embeded nodes

### ISSUE THREAD

**Issue by Lion17** [ethereumjs/merkle-patricia-tree#85]
When you try to call the verifyProof function for a node that is embedded in another node, which in turn is also embedded, an error occurs.

To reproduce:

```
var Trie = require('merkle-patricia-tree')

trie = new Trie()
var ops = [
   { type: 'put', key: 'dog', value: 'puppy' }
 , { type: 'put', key: 'doge', value: 'coin' }
]

trie.batch(ops,
 () => {
  Trie.prove(trie, 'doge', function (err, prove) {
   if (err) console.log(err)
   else
    Trie.verifyProof(trie.root, 'doge', prove, function (err, value) {
     if (err) console.log(err)
     else console.log(value.toString())
    })
  })
 }
)
```

Output:

> node proof.js
> Error: Unexpected end of proof
>     at Object.exports.verifyProof (/home/local/tmp/node_modules/merkle-patricia-tree/proof.js:122:6)
>     at Function.verifyProof (/home/local/tmp/node_modules/merkle-patricia-tree/index.js:56:32)
>     at /home/local/tmp/proof.js:14:10
>     at /home/local/tmp/node_modules/merkle-patricia-tree/proof.js:33:5
>     at /home/local/tmp/node_modules/merkle-patricia-tree/baseTrie.js:520:18
>     at /home/local/tmp/node_modules/async/dist/async.js:473:16
>     at iteratorCallback (/home/local/tmp/node_modules/async/dist/async.js:1064:13)
>     at /home/local/tmp/node_modules/async/dist/async.js:969:16
>     at Object._return [as return] (/home/local/tmp/node_modules/merkle-patricia-tree/baseTrie.js:545:13)
>     at processNode (/home/local/tmp/node_modules/merkle-patricia-tree/baseTrie.js:325:34)

The reason is that only the variant with one level of embedded nodes is considered. This can be seen in file proof.js:82, where the key length is compared with 1, while with multiple nesting of nodes the key will be longer. In our case, it is equal to 2.

**Comment by holgerd77** [comment]
Same here, PR would be great together with a test case. 😄

**Comment by holgerd77** [comment]
Tried to make this example run by updating the code from above to the latest MPT v4 version, came up with to be run in `ts-node`:

```typescript
import { BaseTrie as Trie } from 'merkle-patricia-tree'
import { BatchDBOp } from 'merkle-patricia-tree/db'
const trie = new Trie()

async function run() {
  const ops = [
    { type: 'put', key: Buffer.from('dog'), value: Buffer.from('puppy') },
    { type: 'put', key: Buffer.from('doge'), value: Buffer.from('coin') }
  ] as BatchDBOp[]

  await trie.batch(ops)
  const proof = await Trie.prove(trie, Buffer.from('doge'))
  const value = await Trie.verifyProof(trie.root, Buffer.from('doge'), proof)
  return value
}

run()
.then((value) => {
  console.log(value)
})
.catch((error) => {
    console.log(error)
})
```

This ist *still* not running and we should give this use case another look (and also have a look at the bug here).

1. TypeScript complained about the constant string type definitions in [BatchDBOp](https://github.com/ethereumjs/merkle-patricia-tree/blob/master/src/db.ts#L8) which triggered a cast to `BatchDBOp` to be needed. We might want to generally change the types to be just `string` types //cc @ryanio ?
2. This rose the need to import `BatchDBOp`, was also trickier than I thought, the import from above actually doesn't work yet

**Comment by zmitton** [comment]
Original error should have been taken care of when `proof.js` was eliminated in favor of `basetrie.js` proof implementation. 

Is the issue you're seeing now 

 - (1) an error in the way the trie is getting build, or
 - (2) an error during the verification process

**Comment by zmitton** [comment]
Original error should have been taken care of when proof.js was eliminated in favor of basetrie.js proof implementation.

Is the issue you're seeing now

(1) an error in the way the trie is getting build, or
(2) an error during the verification process
The later is probably something I should look at but I doubt its the case

**Comment by holgerd77** [comment]
@zmitton thanks for the answer, can't remember TBH. Will just leave open here for someone to re-evaluate at some point.
